version: 2.1
orbs:
  rust: {}
  orb-tools: circleci/orb-tools@12.3

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  integration-test_install:
    docker:
      - image: cimg/base:stable
    steps:
      - rust/install
  test-build-with-timing:
    executor:
      name: rust/default
      tag: 1.84.0
    steps:
      - checkout
      - rust/build:
          with_cache: true
          working_directory: sample
          cache_version: timing-v6
      - run: |
          cd sample
          cargo build -vv
  integration-test_test-lint-build:
    parameters:
      nightly-toolchain:
        default: false
        type: boolean
      with_cache:
        default: false
        type: boolean
    executor:
      name: rust/default
      tag: 1.84.0
    steps:
      - checkout
      # - run:
      #     name: Reorganize directory structure
      #     command: mv sample ../sample; cd ..; rm -rf project; mv sample project
      - rust/format:
          nightly-toolchain: <<parameters.nightly-toolchain>>
          working_directory: sample
          cache_version: timing-v6
      - rust/test:
          working_directory: sample
          with_cache: <<parameters.with_cache>>
          cache_version: timing-v6
      - rust/clippy:
          with_cache: <<parameters.with_cache>>
          working_directory: sample
          cache_version: timing-v6
      - rust/build:
          with_cache: <<parameters.with_cache>>
          working_directory: sample
          cache_version: timing-v6
      - rust/cargo-run:
          with_cache: <<parameters.with_cache>>
          working_directory: sample
          cache_version: timing-v6

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - test-build-with-timing:
          filters: *filters
      # - integration-test_install:
      #     filters: *filters
      # - integration-test_test-lint-build:
      #     filters: *filters
      # - integration-test_test-lint-build:
      #     name: integration-lint-build-cache-<<matrix.with_cache>>-toolchain-<<matrix.nightly-toolchain>>
      #     matrix: 
      #       alias: integration-test-matrix
      #       parameters:
      #         with_cache: [true, false]
      #         nightly-toolchain: [true, false]
      #     filters: *filters
      # - rust/lint-test-build:
      #     working_directory: /home/circleci/project/sample
      #     filters: *filters
      #     version: 1.84.0
      # - orb-tools/pack:
      #     filters: *release-filters
      # - orb-tools/publish:
      #     orb_name: circleci/rust
      #     vcs_type: << pipeline.project.type >>
      #     pub_type: production
      #     enable_pr_comment: true
      #     github_token: GHI_TOKEN
      #     requires:
      #       - orb-tools/pack
      #       - integration-test_install
      #       - test-build-with-timing
      #       - integration-test-matrix
      #       - rust/lint-test-build
      #     context: orb-publisher
      #     filters: *release-filters
