description: >
 Build a Rust crate.

parameters:
  crate:
    description: Directory of the create to build.
    default: ""
    type: string
  release:
    description: Whether to build the binary for release or debug.
    type: boolean
    default: false
  with_cache:
    description: Whether to restore and save the cache or not - set to no if running multiple commands in one job.
    type: boolean
    default: true
  cache_version:
    description: Cache version to use - increment this to build a fresh cache.
    type: string
    default: "v1"
  working_directory:
    type: string
    default: "~/project"
    description: Path to the directory containing your Cargo.lock file. Not needed if Cargo.lock lives in the root.

steps:
  - when:
      condition: <<parameters.with_cache>>
      steps:
        - run:
            name: ls -la ~/.cargo
            command: ls -la ~/.cargo
        - restore_cache:
            keys:
              - cargo-<<parameters.cache_version>>-{{ checksum "<<parameters.working_directory>>/Cargo.lock" }}
        - run:
            name: Process cache restore
            command: <<include(scripts/restore_cache.sh)>>
        - run:
            name: ls -la ~/.cargo
            command: ls -la ~/.cargo
  - run:
      name: Cargo Build <<parameters.crate>>
      environment:
        ORB_VAL_CRATE_DIR: <<parameters.crate>>
        ORB_VAL_RELEASE: <<parameters.release>>
      command: <<include(scripts/build.sh)>>
      working_directory: <<parameters.working_directory>>
  - when:
      condition: <<parameters.with_cache>>
      steps:
        - run:
            name: Process cache save
            command: <<include(scripts/save_cache.sh)>>
        - save_cache:
            key: cargo-<<parameters.cache_version>>-{{ checksum "<<parameters.working_directory>>/Cargo.lock" }}
            paths:
              - /tmp/cargo_tmp/
